version: "3"
services: 
  projnotes-image:
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=3000
      - NODE_ENV=development
      - MONGO_USER=projnotes
      - MONGO_PASSWORD=123123
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=projnotes
      - MONGO_INITDB_ROOT_PASSWORD=123123